# Generated by Django 3.1 on 2024-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=200),
        ),
    ]
