# Generated by Django 3.1 on 2024-10-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
