# Generated by Django 3.1 on 2024-10-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_reviewrating'),
        ('Orders', '0002_auto_20241015_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_product',
            name='variation',
        ),
        migrations.AddField(
            model_name='order_product',
            name='variation',
            field=models.ManyToManyField(blank=True, to='Store.Variation'),
        ),
    ]
